### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by andrew-matteson** [scattering/jqplot.science#1]
Hi, 

I'm interested in using some elements of jqplot.science. For my application, I need a license that permits commercial use.

Would it be feasible to add such a license to the repo?

Best,
Andrew

**Comment by bmaranville** [comment]
Hello - I have updated the license information to this, which applies to 
the work in question:

"As a work of the United States Government, this package is in the 
public domain within the United States. Additionally, we waive copyright 
and related rights in the work worldwide through the CC0 1.0 Universal 
public domain dedication (which can be found 
at http://creativecommons.org/publicdomain/zero/1.0/ ). 

Thanks for your interest - Brian Maranville

**Comment by andrew-matteson** [comment]
Thanks!
